version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: ADMIN_USER
      POSTGRES_PASSWORD: ADMIN_PASS
      POSTGRES_DB: stallion-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: