spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stallion
    username: ADMIN_USER
    password: ADMIN_PASS
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true